### ISSUE TITLE
How to use available port number when running Single Server mode?

### ISSUE THREAD

**Issue by a2232189** [kstyrc/embedded-redis#100]
```
RedisExecProvider customProvider = RedisExecProvider.defaultProvider()
                .override(OS.UNIX, "redis-server-3.2.11");
        redisServer = RedisServer.builder().redisExecProvider(customProvider).port(54739).build();
        redisServer.start();
```

I use code above, running program on building server, but got error. Seems that port 54739 has been used. How could I use a available port dynamically?

**Comment by andrewsensus** [comment]
@a2232189 You could try something like
```java
int port = new EphemeralPortProvider().next();
```
and then pass ```port``` in place of ```54739```.

There is probably a race condition in that ```port``` might become unavailable between the time ```redis.embedded.ports.EphemeralPortProvider``` finds it for you and the time ```redisServer.start()``` attempts to use it, but I haven't run into that in practice.
