### ISSUE TITLE
Feature Suggest: Support for Apple Silicon (m1 macBook, aarch64)

### ISSUE THREAD

**Issue by roeniss** [kstyrc/embedded-redis#130]
I wonder if I can add some codes to this repo following this instruction : https://github.com/kstyrc/embedded-redis/issues/127#issuecomment-983825331

Issue https://github.com/kstyrc/embedded-redis/pull/129 seems dead.

**Comment by kenshinji** [comment]
Yeah, please go ahead.

**Comment by roeniss** [comment]
I guess this project is dead totally.

**Comment by Gyuchool** [comment]
I think so too...
