### ISSUE TITLE
Licence - Ok to fork?

### ISSUE THREAD

**Issue by bergetp** [kstyrc/embedded-redis#15]
Hey Kstyrc,

We are currently testing out you embedded-redis in our tests, and it seems to work great. We would probably like to fork this before starting to use it ourselves however.

I can't find a license in this repo, so is it Ok for you if we fork this? Also, there seems to be a 0.6 version on MavenCental which differs from this version. Do you have the official repo in some other place than Github perhaps?

**Comment by kstyrc** [comment]
I've added licence info to README.md. It's Apache 2.0
