### ISSUE TITLE
Logs for redis server

### ISSUE THREAD

**Issue by enisher** [kstyrc/embedded-redis#17]
Now logs of embedded server goes to nowhere. It is very inconvenient, when some issues come up you can't check redis logs to figure out what is the cause.

Running the server with command line argument that specifies path to log is not an option because in this case it doesn't send log to system output, but RedisServer expect logs there to check if it has been activated.

**Comment by kstyrc** [comment]
embedded-redis v0.4 logs errorStream from redis to System.out. Would it help to add possibility to log to a file? How about many redis instances? Separate files?
