### ISSUE TITLE
Write unit tests against all (most of) redis versions

### ISSUE THREAD

**Issue by kstyrc** [kstyrc/embedded-redis#18]
We should include in src/test/resources all (most of?) redis versions and create unit tests for each redis version:
http://redis.io/download

TO CONSIDER:
Which version should we package inside the published JAR in maven?

**Comment by ghillert** [comment]
I think the project should at least track the most recent major versions e.g. `2.8`. I have created the following issue for that: https://github.com/kstyrc/embedded-redis/issues/23

Also, it looks like there may be the need/desire to support multiple Redis versions simultaneously. I see 2 use-cases:

**Would it maybe make sense to externalize just the Redis binaries into their own Maven sub-module?**

That way the main `embedded-redis` project does not have to provide Redis version-specific releases but rather references a transitive dependency containing the recent-Redis binaries. 

However, if users prefer a different Redis binary version, they can just override the transitive dependency.

**Add the ability to provide custom binary locations for all 3 major platforms**

At present you can only specify a single custom binary to be used. As @kstyrc pointed out above - in testing scenarios or for samples, I may have to support all 3 major platforms simultaneously. It would be nice to provide all three binaries, similar to the example above.

**Comment by kstyrc** [comment]
@ghillert 
I've implemented it by adding the ability to provide custom binary locations for all 3 major platforms.

See https://github.com/kstyrc/embedded-redis/pull/29

Would be grateful for feedback
