### ISSUE TITLE
osArch for Windows 7 64 running on 32bits JVM

### ISSUE THREAD

**Issue by pdorgambide** [kstyrc/embedded-redis#20]
The osArch returns "x86" on 64 bits Windows 7 when running on 32bits JVM.
[Beware when detecting 32 and 64 bit OS's in Java](https://blogs.oracle.com/DieterDeramoudt/entry/beware_when_detecting_32_and)

**Comment by kstyrc** [comment]
Oh, thanks! I'll adress that in the next release.
