### ISSUE TITLE
Embed a more recent version of Redis

### ISSUE THREAD

**Issue by ghillert** [kstyrc/embedded-redis#23]
We use `embedded-redis` for testing and our samples. In one of our projects (https://github.com/spring-projects/spring-session), we also use Redis keyspace notifications, and therefore require Redis `2.8.0+`. 

Considering that Redis `2.8` was released in 2013, could you please add the binaries of a more recent Redis version? That would help use a lot! 

I am aware that one can provide their own Redis binaries. But for testing and samples, I would need to provide versions for all 3 major platforms. This is a bit cumbersome right now - as it currently involves testing for those 3 platforms in my own code. I cannot even reuse some of the provided utility methods such as `RedisRunScriptEnum#getRedisRunScript()`, as it is private.

**Comment by domdorn** [comment]
This is also bugging me!
It looks like @kstyrc  already added recent versions (2.8.19) .. 
@kstyrc could you please bundle a release, so we can upgrade our dependencies? 
Thanks a lot!

**Comment by kstyrc** [comment]
Hi,

I've just released current master branch into 0.4 version. However, the PGP signing can have issues... I lost my previous PGP key ;<

**Comment by thekalinga** [comment]
I pulled the 0.4 version. the windows version seems to be of older versions. Not 2.8+.

Do u have any plans of adding windows support aswell?

**Comment by kstyrc** [comment]
Seems so. Would https://github.com/MSOpenTech/redis/releases/tag/win-2.8.17.4 (latest release) be enough? I can't test it on Windows myself ;<

**Comment by t4gedieb** [comment]
@kstyrc I tested it with release https://github.com/MSOpenTech/redis/releases/tag/win-2.8.19 and it works without problems

**Comment by kstyrc** [comment]
Thanks, I'll include that in the next release. Hope to make it through weekend.

**Comment by jonneyzhang** [comment]
@kstyrc  I need  your help  ,first  the redis.jar for 0.4 cannot work in the environment of windows ,and then  i test 0.6 ,it cannot work as well  ,so  I hope you can help solve the problem  thank you very much,
my email is 1078030014@qq.com(you can communicate with me by it ) , i am looking forward to your reply ,

**Comment by jonneyzhang** [comment]
![image](https://cloud.githubusercontent.com/assets/11514106/6747271/bab3651a-cf11-11e4-92fd-f8dbcba77035.png)

**Comment by t4gedieb** [comment]
@jonneyzhang This project contains the Redis Windows version 2.6. You need to wait until the version has been updated to 2.8.

In the meantime you can use a manual Redis installation as described in the README.md:
```java
redisServer = new RedisServer(new File("path/to/your/redis-server.exe"), Protocol.DEFAULT_PORT);
```

**Comment by jonneyzhang** [comment]
thanks for your reply very much,I will try out it. Due to I am a newer to the world of spring, so thanks for those  volunteer  improving and perfecting the function of spring   including you

**Comment by rwinch** [comment]
@kstyrc Any news on getting a release with an updated Redis version for Windows?

**Comment by kstyrc** [comment]
@rwinch @jonneyzhang I've just release version 0.5 where windows binary got updated to 2.8.19. Let me know of any issues (I can't check it on windows myself).

**Comment by rwinch** [comment]
@kstyrc Thanks for the quick turnaround. I am unfortunately unable to verify either since my Windows VM is a 32 bit install. Hopefully someone else will be able to verify the update.

If you get time and are interested, I have heard good things about http://www.appveyor.com/ for running a CI build on a Windows machine. I'm not certain how easy it would be to setup, but may be worth looking into.

**Comment by kstyrc** [comment]
@rwinch Thanks for appveyor suggestion. It's great. I've added Travis (Linux) & AppVeyor (Windows) build status badges to README page. I'll take me a bit more effort to experiment with platform matrix (x86, x64) and with stabilizing the build for Windows (spurious failures).

**Comment by rwinch** [comment]
@kstyrc Awesome! I'm glad to hear it appears to be of use :)
