### ISSUE TITLE
Release to maven central.

### ISSUE THREAD

**Issue by paranoiabla** [kstyrc/embedded-redis#37]
Hi,

would it be possible to release the artifacts to maven central? My build has tons of dependencies and I don't really like adding a new repository.

**Comment by kstyrc** [comment]
Sure, I'll look into that. What should be the groupId? I guess that for official maven central you gotta be the owner of the domain? Unfortunately, I have no domain for embedded-redis..

**Comment by paranoiabla** [comment]
I don't think you need to be the owner of a domain. At least not according to this one:
https://maven.apache.org/guides/mini/guide-naming-conventions.html

**Comment by kstyrc** [comment]
I've submitted a request to Sonatype:
https://issues.sonatype.org/browse/OSSRH-14938

**Comment by kstyrc** [comment]
I've released 0.6 to OSS Sonatype but still pending a sync with Maven Central:
https://github.com/kstyrc/embedded-redis/pull/39#issuecomment-91701398

**Comment by kstyrc** [comment]
0.6 release got synced with Maven Central:
http://repo.maven.apache.org/maven2/com/github/kstyrc/embedded-redis/0.6/

```xml
<dependency>
  <groupId>com.github.kstyrc</groupId>
  <artifactId>embedded-redis</artifactId>
  <version>0.6</version>
</dependency>
```

**Comment by kstyrc** [comment]
#41 #42
