### ISSUE TITLE
Support Older JDK versions

### ISSUE THREAD

**Issue by rwinch** [kstyrc/embedded-redis#38]
Using JDK 8 definitely has its niceties, but building with JDK 8 sets unnecessary limitations on who can use embedded Redis.

I'd really like to see JDK 6+ supported. If you agree, I'd be glad to put a PR together.

**NOTE:** Many claim that JDK 6 is EOL, but that [isn't really true](https://spring.io/blog/2015/04/01/ongoing-support-for-java-7-and-even-java-6).

**Comment by kstyrc** [comment]
That was my concern when accepting PR about adding Sentinel support. I guess that downgrading to JDK 6 won't require many changes?

**Comment by rwinch** [comment]
It appears there are quite a few (51) errors when switching to JDK 6. Most of the changes should be rather straight forward though (i.e. "< >" operators are not allowed below 1.7, switching lambda to an object, etc)

**Comment by rwinch** [comment]
PS Let me know if you agree I can get a PR put together (unless you prefer to do the work).

**Comment by kstyrc** [comment]
I agree. Let's do this. Your PR is more than welcome.

**Comment by rwinch** [comment]
I submitted a #39 to resolve this.

I am planning to release Spring Session Tuesday of next week. I'd love to update the sample applications to use 0.6 so that they work with older JDK versions. If there is any changes we could get a release before  then, it would be **very** much appreciated!
