### ISSUE TITLE
Publish the release 0.6 on repository

### ISSUE THREAD

**Issue by robsonpeixoto** [kstyrc/embedded-redis#46]
The repository https://clojars.org/redis.embedded/embedded-redis still on version 0.5

**Comment by kstyrc** [comment]
I think it's no longer necessary to publish to clojars if embedded-redis is in Maven Central:
http://mvnrepository.com/artifact/com.github.kstyrc/embedded-redis/0.6

Or is it so important?

**Comment by robsonpeixoto** [comment]
Thanks @kstyrc. My bad. On my `pom.xml` are configured the old repository.
