### ISSUE TITLE
Running on Jenkins glibc version not found

### ISSUE THREAD

**Issue by larry13767** [kstyrc/embedded-redis#49]
Hi

I can run this locally on my mac but once i check it in and run it on Jenkins, I see the following error message.

/tmp/1430170830037-0/redis-server-2.8.19: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/1430170830037-0/redis-server-2.8.19)

We are running with Spring 4.1.5 and Java 8

What are the OS dependencies?

**Comment by kstyrc** [comment]
Redis claims on its page that it has no deps other than GCC and libc. I guess you have too old libc version on your Jenkins server? It requires at least 2.14.

**Comment by larry13767** [comment]
yes, they are at 2.12.  I am trying to get them to upgrade.  Big companies :)
Thanks

**Comment by thiyaml** [comment]
Do we have an option if we want to have 2.14 on a separate folder & only embedded server uses this lib?

**Comment by kstyrc** [comment]
Will try to find a way according to:
http://stackoverflow.com/questions/847179/multiple-glibc-libraries-on-a-single-host

**Comment by rainhacker** [comment]
@kstyrc  @EvilJinious1 Were you able to resolve this ? If you managed to install 2 glibc versions, how did you pointed redis-server to use the desired version of glibc ?
