### ISSUE TITLE
Hanging thread on shutdown in Tomcat

### ISSUE THREAD

**Issue by adsgreen** [kstyrc/embedded-redis#50]
The abstract Redis instance contains a single thread pool:

private final ExecutorService executor = Executors.newSingleThreadExecutor();

This creates a non daemon thread and there is no call to executor.shutdown() in the stop method.
As such this causes an appserver with an embedded redis server to hang.

**Comment by kstyrc** [comment]
Hmm, valid case. Thanks for pointing out I'll try to make ExecutorService running daemon threads.
