### ISSUE TITLE
packaged redis-server.exe wont start

### ISSUE THREAD

**Issue by sparmboy** [kstyrc/embedded-redis#52]
When running the packaged windows binary that comes with the latest release, the following message is displayed:

	The Windows version of Redis allocates a memory mapped heap for sharing with
	the forked process used for persistence operations. In order to share this
	memory, Windows allocates from the system paging file a portion equal to the
	size of the Redis heap. At this time there is insufficient contiguous free
	space available in the system paging file for this operation (Windows error
	0x5AF). To work around this you may either increase the size of the system
	paging file, or decrease the size of the Redis heap with the --maxheap flag.
	Sometimes a reboot will defragment the system paging file sufficiently for
	this operation to complete successfully.

	Please see the documentation included with the binary distributions for more
	details on the --maxheap flag.

	Redis can not continue. Exiting.

This can be bypassed by adding the ```--maxheap``` option as suggested. 

The config should be extended to be able to specify this argument when starting the server.

**Comment by kstyrc** [comment]
Thanks for the info! Including this in the next release - coming out soon I hope. I'm considering to enable RedisServer user to provide any cmd line paramter.

**Comment by krazyhe** [comment]
'''
server = RedisServer.builder()
                .setting("maxheap 512M")
                .build();
'''

**Comment by sparmboy** [comment]
Yup that worked! Bit of a RTFM. Thanks

**Comment by maxim5** [comment]
It's actually `maxmemory` instead of `maxheap`. See https://github.com/kstyrc/embedded-redis/issues/77

**Comment by saurabh-sp-tripathi** [comment]
How do set such configuration for RedisCluster?
