### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by Sytten** [kstyrc/embedded-redis#75]
Hi!

I need an embedded redis in one on my projects. I was just wondering if the support will continue for the current repository. If not, it would be good to find new maintainers.
I saw an active fork here https://github.com/fmonniot/embedded-redis
But its a no go for me since it does not provide embedded redis binaries nor spring support.

Thanks!

**Comment by robertotru** [comment]
I would say that yes, it is abandoned. It is a pity, indeed.

**Comment by maksymkovalenko** [comment]
See https://github.com/kstyrc/embedded-redis/issues/82 for latest updates on this. I'd suggest to close this issue in favor of that one.
