### ISSUE TITLE
[Discussion] Project abandonment / maintenance

### ISSUE THREAD

**Issue by tkroman** [kstyrc/embedded-redis#82]
Looks like this project is no longer maintained. @kstyrc correct me if I'm wrong. 

If that is true, I'd like to start a discussion to see how much people are interested in a possible fork or ownership transfer so the community can take care of the further evolution.

To everyone interested: please voice your opinions on the matter.

**Comment by MagnusSmith** [comment]
It would be great to see this continue and get updated.  It's so useful

**Comment by MagnusSmith** [comment]
Happy to help

**Comment by clamey** [comment]
I'm up for helping as well - looks like there's a bunch of forks:

https://github.com/kstyrc/embedded-redis/network

This one seems to have the most work behind it:

https://github.com/fmonniot/embedded-redis

**Comment by tkroman** [comment]
Seeing as this hasn't got attention from the author, I think we are free to proceed as we see it fit. I'all do a fork and update to the latest stable redis binary and try to publish. I'll also post an update here to redirect fresh issues to the fork's tracker. Suggestions welcome :)

**Comment by clamey** [comment]
Sounds good

**Comment by MagnusSmith** [comment]
Very good

**Comment by krzysztof-styrc** [comment]
Sorry for a late reply.

Since long ago I have no time to devote to this project. If you still wanna develop it feel free to fork it. But on the other hand, it would be great to keep it in this repository to guarantee maven repository continuation.

**Comment by clamey** [comment]
@krzysztof-styrc completely understand, life can get busy - thanks for getting the project this far, it's very useful!

I'm kind of leaning to a new fork that's not dependent on a user path and then pointing people to that, but am open to whatever folks want.

**Comment by tkroman** [comment]
@krzysztof-styrc Did you build cross-platform binaries yourself?

@clamey @MagnusSmith what are your preferred platforms? I have neither resources nor a burning desire to support windows, so this may be a blocker. If someone else thinks they could do it, that's great.

**Comment by MagnusSmith** [comment]
There is the Microsoft port of Redis [here](https://github.com/MSOpenTech/redis) 
One can then use chocolately [here](https://chocolatey.org/packages/redis-64) to install the latest redis.
This creates a redis-64 directory that includes the redis-server.exe.  I have not tested but I'm pretty sure that renaming this with the version suffix should do the job.

**Comment by tkroman** [comment]
@MagnusSmith yeah, I'm aware of that, but I see the issue in the fact that windows redis binaries may lag behind the latest stable ones, e.g. current stable is 3.2.8 and the MSOpenTech's is 3.2.1. And, as I said, I have no access to the windows machine and all this fuss with VMs may be too much for me as a person who would never use aspect of the library.

**Comment by MagnusSmith** [comment]
@tkroman I'm happy to try and support the Windows binaries.  It looks like from the RedisExecProvider that we can either attempt a lowest common denominator approach for all platforms or target specific redis versions for different platforms.

**Comment by clamey** [comment]
I don't have ready access to Windows - I'm in Linux and OS X land...

**Comment by clamey** [comment]
To be clear, I meant the distribution artifact name probably shouldn't be tied to a specific user.  The GitHub project will have to be under a user - I just think the project will need more than one collaborator who can approve PRs and do releases to avoid a bottle neck.

**Comment by maksymkovalenko** [comment]
It's practical to start small  and just upgrade to latest Redis and Java 8.
It's easy and important.

Other suggestions are all good, but can be discussed as the subsequent steps.

@krzysztof-styrc @kstyrc can we start with just this?
Let me know how i can help with this.

**Comment by tkroman** [comment]
So if we find someone who can provide us with windows builds, that would mean we aren't blocked on anything else. I myself can do OS X builds (and linux, with some effort).

**Comment by maksymkovalenko** [comment]
i'll do linux

**Comment by tkroman** [comment]
Sooo... windows anyone?

**Comment by MagnusSmith** [comment]
I'll do windows.

**Comment by lucasweb78** [comment]
Has the work discussed above started? Is there a fork that the work is being done on? I Would be interested in both using it and contributing.

**Comment by tkroman** [comment]
@lucasweb78  @MagnusSmith @maksymkovalenko sorry guys, got buried in work. I think I could find some time to do a Mac OS build & perhaps fork a project, if that's really necessary.

@krzysztof-styrc @kstyrc how about distribution? If we did a collective PR with fresh binaries, would you mind releasing an artifact?

Also, guys, WDYT about providing builds for 2.x, 3.x & 4.x simultaneously?

**Comment by emjburns** [comment]
@MagnusSmith can you provide a windows binary for Redis 3.2.11? @kstyrc will be merging my PR for 3.2.11 and releasing in a couple of days.

**Comment by maksymkovalenko** [comment]
@tkroman I just created PR #110 that adds support for all Redis versions, I added binaries for Linux 64 only (don't have access to Win, Mac OS).
@krzysztof-styrc @kstyrc Please take a look when you have a chance.

**Comment by emjburns** [comment]
@maksymkovalenko we forked last year under our github organization (https://github.com/spinnaker/embedded-redis) and are building artifacts/etc. You are welcome to submit PRs to our repo.

**Comment by maksymkovalenko** [comment]
Ha-ha, too many new changes on your fork! :) I'll probably have to redo quite a bit of my PR.
But thanks, will rely on this fork.
