### ISSUE TITLE
Seeking Advice: Windows firewall?

### ISSUE THREAD

**Issue by concon121** [kstyrc/embedded-redis#98]
First off, this package does exactly what I want it to, so kudos for that!

I'm having issues with windows firewall keep prompting that embedded-redis wants access.  Basically I think that the issue stems from the fact that it seems to copy the .exe to a temporary location every time that you create a new redis server?  The name of the .exe file changes every time, I guess its based on a timestamp or something, so windows firewall thinks its a new thing every time rather than remembering that you allowed embedded-redis access last time.

I've resolved this for now by simply allowing connections on the port i'm using, but i'm not really happy with this as a solution as anything can connect to that port, rather than just redis.

Do you have advice on how to resolve this issue?

**Comment by alturkovic** [comment]
Try binding it to a port, this helped me:
```
RedisServer.builder()
      .setting("bind 127.0.0.1")
      .port(SocketUtils.findAvailableTcpPort())
      .build();
```

**Comment by BernhardBln** [comment]
Had the same problem on Mac, it also resolved the issue there, thanks :)

**Comment by concon121** [comment]
Fixed my issue, thanks kind strangers!
